Repository LMAX-Exchange/disruptor, pull requests merged in 2021-04, with the labels that each got.

#360 Add method to check if disruptor has been started
  src/main/java/com/lmax/disruptor/dsl/Disruptor.java
  src/test/java/com/lmax/disruptor/dsl/DisruptorTest.java
Labels: enhancement

#361 Update Badge links in readme
  README.md
Labels: documentation

#356 Increase MultiProducerSequencer performance on getting next sequence (master branch)
  src/jmh/java/com/lmax/disruptor/MultiProducerSingleConsumer.java
  src/main/java/com/lmax/disruptor/MultiProducerSequencer.java
  src/main/java/com/lmax/disruptor/Sequence.java
  src/test/java/com/lmax/disruptor/RingBufferTest.java
  src/test/java/com/lmax/disruptor/SequencerTest.java
Labels: performance

#362 Use platform logging API in FatalExceptionHandler and IgnoreExceptionHandler
  CHANGELOG.md
  src/main/java/com/lmax/disruptor/FatalExceptionHandler.java
  src/main/java/com/lmax/disruptor/IgnoreExceptionHandler.java
Labels: enhancement

#371 Fix #370: Logger instances are lazily initialized
  src/jcstress/java/com/lmax/disruptor/LoggerInitializationStress.java
  src/main/java/com/lmax/disruptor/BatchEventProcessor.java
  src/main/java/com/lmax/disruptor/ExceptionHandlers.java
  src/main/java/com/lmax/disruptor/dsl/ExceptionHandlerWrapper.java
Labels: enhancement
